name: Automaatselt uuenda README faili

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Klooni repo
        uses: actions/checkout@v4

      - name: Lisa täitmisõigus skriptile
        run: chmod +x add_to_readme.sh

      - name: Käivita README genereerimise skript
        run: bash add_to_readme.sh

      - name: Pushi uuendatud README
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git

